import json
import re
import time
from datetime import datetime
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

import httpx
import yaml

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from agents.base import SkillAgent
from api.dependencies import get_current_user, get_db, get_project_context
from api.routers.api_keys import get_user_secret
from api.utils.knowledge import fetch_knowledge
from core.db.models import Keyword, PageChange, User
from core.models.context import ProjectContext
from core.secrets import SecretManager
from integrations.cms.wordpress import WordPressAdapter
from integrations.base import IntegrationError
from shared.exceptions import SecretNotFoundError

router = APIRouter(prefix="/projects/{name}/improve", tags=["improve"])


# ── Helpers ───────────────────────────────────────────────────────────────────

def _get_wp_adapter(context: ProjectContext) -> WordPressAdapter:
    wp_cfg = context.config.integrations.wordpress
    if not wp_cfg.enabled:
        raise HTTPException(400, "WordPress integration is not connected. Go to Integrations tab first.")
    secrets = SecretManager()
    try:
        return WordPressAdapter(
            url=wp_cfg.url,
            username=secrets.get(wp_cfg.username_env),
            password=secrets.get(wp_cfg.password_env),
        )
    except (SecretNotFoundError, Exception) as e:
        raise HTTPException(400, f"WordPress credentials error: {e}")


_BUILDERS_CONFIG: list[dict] = []
_BUILDERS_LOADED_AT: float = 0.0
_BUILDERS_TTL: int = 300  # seconds — YAML changes go live within 5 minutes, no restart needed
_BUILDERS_YAML = Path(__file__).parent.parent.parent / "config" / "builders.yaml"


def _get_builders() -> list[dict]:
    global _BUILDERS_CONFIG, _BUILDERS_LOADED_AT
    if not _BUILDERS_CONFIG or time.time() - _BUILDERS_LOADED_AT > _BUILDERS_TTL:
        with open(_BUILDERS_YAML) as f:
            _BUILDERS_CONFIG = yaml.safe_load(f)["builders"]
        _BUILDERS_LOADED_AT = time.time()
    return _BUILDERS_CONFIG


def _detect_builder(content: str) -> str:
    builders = _get_builders()
    for b in builders:
        if b.get("fallback"):
            continue
        if any(sig in content for sig in b.get("detects", [])):
            return b["name"]
    fallback = next((b for b in builders if b.get("fallback")), {"name": "classic"})
    return fallback["name"]


def _visible_word_count(html: str) -> int:
    return len(re.sub(r'<[^>]+>', ' ', html).split())


def _detect_page_profile(post_data: dict, is_hub: bool, hub_existing_url: str) -> dict:
    """
    Build a capability profile from the WordPress page data before running any agents.
    Determines what the system can do for this specific page at zero AI cost.
    """
    is_homepage = is_hub and not urlparse(hub_existing_url).path.strip("/")
    is_posts_page = post_data.get("is_posts_page", False)
    content = post_data.get("content", "")
    word_count = _visible_word_count(content)
    is_theme_controlled = is_homepage and word_count < 100

    builder = _detect_builder(content)
    builder_cfg = next((b for b in _get_builders() if b["name"] == builder), {})
    # Posts listing pages are never content-editable — WordPress core generates the loop
    content_editable = (
        builder_cfg.get("content_editable", False)
        and not is_theme_controlled
        and not is_posts_page
    )

    has_yoast = post_data.get("has_yoast", False)
    has_rankmath = post_data.get("has_rankmath", False)
    seo_plugin = "yoast" if has_yoast else ("rankmath" if has_rankmath else "none")
    meta_editable = seo_plugin != "none"

    can_improve = content_editable or meta_editable

    blocked_reason: str | None = None
    if not can_improve:
        if is_posts_page:
            blocked_reason = (
                "This is your blog listing page — its content is auto-generated by WordPress. "
                "No Yoast SEO or RankMath plugin was found. "
                "Install Yoast SEO or RankMath to enable automatic SEO title and description updates."
            )
        elif builder in ("elementor", "divi", "wpbakery"):
            blocked_reason = (
                f"{builder.title()} page builder detected — content editing is not yet supported for this builder. "
                f"No Yoast SEO or RankMath plugin was found either. "
                f"Install Yoast SEO or RankMath to enable automatic SEO title and description updates."
            )
        elif is_theme_controlled:
            blocked_reason = (
                "This homepage content is managed by your theme template — "
                "post_content edits are not rendered on the frontend. "
                "No Yoast SEO or RankMath plugin was found. "
                "Install Yoast SEO or RankMath to enable automatic SEO title and description updates."
            )
        else:
            blocked_reason = (
                "No improvements possible: page content is not editable and no SEO plugin (Yoast/RankMath) is active."
            )

    return {
        "seo_plugin": seo_plugin,
        "builder": builder,
        "is_homepage": is_homepage,
        "is_theme_controlled": is_theme_controlled,
        "is_posts_page": is_posts_page,
        "content_editable": content_editable,
        "meta_editable": meta_editable,
        "can_improve": can_improve,
        "blocked_reason": blocked_reason,
    }


def _wp_push(wp: WordPressAdapter, record: PageChange, content: str) -> None:
    if record.wp_post_type == "page":
        wp.update_page(record.wp_post_id, content)
    else:
        wp.update_post(record.wp_post_id, content)


_REFRESH_CADENCE = {
    "meta": 60,     # minimum days between meta title/description updates
    "content": 90,  # minimum days between content improvements
    "cluster": 90,  # minimum days between keyword re-clustering
}


def _compute_refresh_status(wp_post_id: int, history: list[PageChange]) -> dict:
    """
    Returns per-action readiness based on days since last improvement for this page.
    `history` must be the pre-analysis snapshot (before the current run created new records).
    """
    last = next(
        (c for c in history if c.wp_post_id == wp_post_id and c.status in ("pending", "approved")),
        None,
    )

    if not last:
        return {
            "days_since_last_improvement": None,
            "meta":    {"min_days": _REFRESH_CADENCE["meta"],    "ready": True, "days_remaining": 0},
            "content": {"min_days": _REFRESH_CADENCE["content"], "ready": True, "days_remaining": 0},
            "cluster": {"min_days": _REFRESH_CADENCE["cluster"], "ready": True, "days_remaining": 0},
            "overall_action": "first_time",
            "message": "This page has not been improved before — run freely.",
        }

    days = max(0, (datetime.utcnow() - last.created_at).days)
    meta_rem    = max(0, _REFRESH_CADENCE["meta"]    - days)
    content_rem = max(0, _REFRESH_CADENCE["content"] - days)
    cluster_rem = max(0, _REFRESH_CADENCE["cluster"] - days)

    if days < 30:
        action = "too_soon"
        message = (
            f"Last improved {days} day(s) ago. "
            f"Wait at least {30 - days} more day(s) before re-running any improvements."
        )
    elif days < _REFRESH_CADENCE["meta"]:
        action = "too_soon"
        message = (
            f"Last improved {days} day(s) ago. "
            f"Meta refresh ready in {meta_rem} day(s). "
            "Tip: if GSC CTR drops ≥40% below the position benchmark, meta can be refreshed sooner."
        )
    elif days < _REFRESH_CADENCE["content"]:
        action = "meta_ready"
        message = (
            f"Last improved {days} day(s) ago. "
            f"Meta title/description ready to refresh now. "
            f"Full content improvement ready in {content_rem} day(s)."
        )
    elif days < 180:
        action = "improve_now"
        message = (
            f"Last improved {days} day(s) ago. "
            "Meta + content improvements are both ready to re-run."
        )
    else:
        action = "rewrite_eligible"
        message = (
            f"Last improved {days} day(s) ago. "
            "Consider a full content rewrite if position is stuck at 31+ with declining impressions."
        )

    return {
        "days_since_last_improvement": days,
        "meta":    {"min_days": _REFRESH_CADENCE["meta"],    "ready": meta_rem == 0,    "days_remaining": meta_rem},
        "content": {"min_days": _REFRESH_CADENCE["content"], "ready": content_rem == 0, "days_remaining": content_rem},
        "cluster": {"min_days": _REFRESH_CADENCE["cluster"], "ready": cluster_rem == 0, "days_remaining": cluster_rem},
        "overall_action": action,
        "message": message,
    }


def _change_history_block(history: list[PageChange]) -> str:
    if not history:
        return "No previous improvements made to this page."
    lines = ["Previous improvements (most recent first):"]
    for c in history:
        lines.append(f"- [{c.created_at.strftime('%Y-%m-%d')}] {c.change_summary} (status: {c.status})")
    return "\n".join(lines)


def _knowledge_block(db: Session, user_id: int, project_name: str) -> str:
    kb = fetch_knowledge(db, user_id, project_name)
    if not kb:
        return ""
    parts = []
    if kb.about:             parts.append(f"About: {kb.about.strip()}")
    if kb.products_services: parts.append(f"Products/Services: {kb.products_services.strip()}")
    if kb.target_audience:   parts.append(f"Target Audience: {kb.target_audience.strip()}")
    if kb.brand_voice:       parts.append(f"Brand Voice: {kb.brand_voice.strip()}")
    if kb.competitors_notes: parts.append(f"Competitors: {kb.competitors_notes.strip()}")
    if kb.seo_context:       parts.append(f"SEO Context: {kb.seo_context.strip()}")
    return "\n".join(parts) if parts else ""


_WP_COMMENT_RE = re.compile(r'<!--\s*/?wp:[^>]*?-->')
_HTML_ATTR_RE  = re.compile(r'\s+(?:class|style|data-[a-zA-Z0-9_-]+)="[^"]*"')
_IMG_TAG_RE    = re.compile(r'<img[^>]*>', re.IGNORECASE)
_ALT_ATTR_RE   = re.compile(r'\balt\s*=\s*["\']([^"\']*)["\']', re.IGNORECASE)
_HREF_RE       = re.compile(r'''href\s*=\s*["']([^"']+)["']''', re.IGNORECASE)


def _strip_html_for_analysis(html: str) -> str:
    html = _WP_COMMENT_RE.sub('', html)
    html = _HTML_ATTR_RE.sub('', html)
    return html


# ── Snapshot helpers (Python-computed, zero AI cost) ──────────────────────────

def _count_keyword_frequency(html: str, keyword: str) -> int:
    """Count how many times keyword appears in visible text (case-insensitive)."""
    if not keyword:
        return 0
    text = re.sub(r'<[^>]+>', ' ', html).lower()
    return text.count(keyword.lower())


def _count_images_missing_alt(html: str) -> int:
    """Count <img> tags with no alt attribute or an empty alt value."""
    missing = 0
    for m in _IMG_TAG_RE.finditer(html):
        alt = _ALT_ATTR_RE.search(m.group())
        if not alt or not alt.group(1).strip():
            missing += 1
    return missing


# ── Link-scan helpers ─────────────────────────────────────────────────────────

def _extract_links(html: str, page_url: str) -> list[dict]:
    """Return unique hrefs from content, each tagged as internal or external."""
    base = urlparse(page_url)
    seen: set[str] = set()
    links: list[dict] = []
    for m in _HREF_RE.finditer(html):
        href = m.group(1).strip()
        if not href or href.startswith('#'):
            continue
        parsed = urlparse(href)
        if parsed.scheme and parsed.scheme not in ("http", "https"):
            continue
        if not parsed.scheme:
            # root-relative → absolutise
            href = f"{base.scheme}://{base.netloc}/{href.lstrip('/')}"
            parsed = urlparse(href)
        if href in seen:
            continue
        seen.add(href)
        is_internal = parsed.netloc == base.netloc
        links.append({"url": href, "type": "internal" if is_internal else "external"})
    return links


def _check_link_status(url: str) -> int:
    """
    HTTP HEAD check. Falls back to GET on 405.
    Returns status code, 0 for timeout, -1 for connection error.
    """
    try:
        resp = httpx.head(url, follow_redirects=True, timeout=4,
                          headers={"User-Agent": "SEO-OS/1.0"})
        if resp.status_code == 405:
            resp = httpx.get(url, follow_redirects=True, timeout=4,
                             headers={"User-Agent": "SEO-OS/1.0"})
        return resp.status_code
    except httpx.TimeoutException:
        return 0
    except Exception:
        return -1


def _run_meta_only(
    keyword: str,
    post_data: dict,
    profile: dict,
    knowledge_block: str,
    openai_key: str,
    user_id: int,
    project_name: str,
    cluster_name: str,
    project,
    db: Session,
) -> PageChange:
    meta_msg = f"""## main_keyword
{keyword}

## page_title
{post_data['title']}

## is_homepage
{str(profile['is_homepage']).lower()}

## current_meta_title
{post_data.get('current_meta_title', '')}

## current_meta_description
{post_data.get('current_meta_description', '')}

## business_context
{knowledge_block}
"""
    try:
        raw = SkillAgent("seo-meta", openai_key, model="gpt-4o-mini").run(
            meta_msg, timeout=60, json_mode=True
        )
        result = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"seo-meta agent returned invalid JSON: {e}")

    meta_title = (result.get("suggested_meta_title") or "").strip()
    meta_description = (result.get("suggested_meta_description") or "").strip()
    current_title = (post_data.get("current_meta_title") or "").strip()
    current_description = (post_data.get("current_meta_description") or "").strip()
    title_changed = meta_title and meta_title != current_title
    desc_changed = meta_description and meta_description != current_description

    plugin_label = "Yoast" if profile["seo_plugin"] == "yoast" else "RankMath"
    meta_updates = None
    changes_made: list[str] = []

    if title_changed or desc_changed:
        meta_updates = {
            "plugin": profile["seo_plugin"],
            "original_meta_title": current_title or None,
            "original_meta_description": current_description or None,
            "suggested_meta_title": meta_title if title_changed else None,
            "suggested_meta_description": meta_description if desc_changed else None,
        }
        changes_made.append(f"seo_meta: SEO title and description queued for {plugin_label} update.")

    if meta_updates:
        if profile.get("is_posts_page"):
            change_summary = (
                f"Blog listing page — content is auto-generated by WordPress, not editable. "
                f"New SEO title and description queued for {plugin_label}."
            )
        elif profile["is_theme_controlled"]:
            change_summary = (
                f"Homepage content is managed by your theme template — post_content edits are not visible on the frontend. "
                f"New SEO title and description queued for {plugin_label}."
            )
        else:
            change_summary = (
                f"{profile['builder'].title()} page detected — content editing is not yet supported for this builder. "
                f"New SEO title and description queued for {plugin_label}."
            )
    else:
        if profile.get("is_posts_page"):
            change_summary = (
                f"Blog listing page — content is auto-generated by WordPress. "
                f"Current {plugin_label} meta is already well-optimized — no changes suggested."
            )
        elif profile["is_theme_controlled"]:
            change_summary = (
                f"Homepage content is managed by your theme template. "
                f"Current {plugin_label} meta is already well-optimized — no changes suggested."
            )
        else:
            change_summary = (
                f"{profile['builder'].title()} page — content editing not supported for this builder. "
                f"Current {plugin_label} meta is already well-optimized — no changes suggested."
            )

    record = PageChange(
        user_id=user_id,
        project_name=project_name,
        cluster_name=cluster_name,
        wp_post_id=post_data["id"],
        wp_post_url=post_data["link"],
        wp_post_type=post_data["type"],
        original_content=post_data["content"],
        new_content=post_data["content"],
        change_summary=change_summary,
        changes_made=changes_made,
        statistics={
            "keyword_frequency": _count_keyword_frequency(post_data.get("content", ""), keyword),
            "images_missing_alt": _count_images_missing_alt(post_data.get("content", "")),
            **({"current_meta_title": current_title} if current_title else {}),
            **({"current_meta_description": current_description} if current_description else {}),
        },
        meta_updates=meta_updates,
        status="pending" if meta_updates else "no_action",
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    return record


def _run_page_pipeline(
    keyword: str,
    secondary_keywords: str,
    post_data: dict,
    pillar_url: str,
    history: list,
    project,
    openai_key: str,
    user_id: int,
    project_name: str,
    cluster_name: str,
    db: Session,
    is_hub: bool = False,
    hub_existing_url: str = "",
    seo_plugin: str = "none",
) -> PageChange:
    # Override per-page detection with the authoritative namespace-based result
    post_data["has_yoast"] = seo_plugin == "yoast"
    post_data["has_rankmath"] = seo_plugin == "rankmath"
    profile = _detect_page_profile(post_data, is_hub, hub_existing_url)
    current_date = datetime.utcnow().strftime("%B %Y")

    # Two-pass builder detection:
    # Pass 1 (already done in _detect_page_profile) reads post_content from the REST API.
    # Pass 2 fetches the rendered public page when post_content is too short to be reliable
    # (< 30 words). Elementor, SeedProd, and others store data outside post_content, so
    # post_content is empty even though the live page has hundreds of words.
    # Skip Pass 2 for posts listing pages — their empty post_content is by design, not a builder.
    raw_word_count = _visible_word_count(post_data.get("content", ""))
    if raw_word_count < 30 and post_data.get("link") and not profile.get("is_posts_page"):
        try:
            rendered_resp = httpx.get(
                post_data["link"], follow_redirects=True, timeout=10,
                headers={"User-Agent": "Mozilla/5.0 SEO-OS/1.0"},
            )
            if rendered_resp.is_success:
                rendered_html = rendered_resp.text
                rendered_builder = _detect_builder(rendered_html)
                builder_cfg = next((b for b in _get_builders() if b["name"] == rendered_builder), {})
                if not builder_cfg.get("content_editable", True):
                    # Known builder detected in rendered HTML — mark as non-editable
                    profile["builder"] = rendered_builder
                    profile["content_editable"] = False
                    profile["can_improve"] = profile["meta_editable"]
                    if not profile["can_improve"]:
                        profile["blocked_reason"] = (
                            f"{rendered_builder.title()} page builder detected — content editing is not "
                            "supported. Install Yoast SEO or RankMath to enable meta updates."
                        )
                elif _visible_word_count(rendered_html) > 200:
                    # Rendered page has substantial content but no known builder was identified.
                    # Treat as unknown builder — safe default: do not touch post_content.
                    profile["builder"] = "unknown-builder"
                    profile["content_editable"] = False
                    profile["can_improve"] = profile["meta_editable"]
                    if not profile["can_improve"]:
                        profile["blocked_reason"] = (
                            "Page content appears to be managed by an unrecognised page builder "
                            "(post_content is empty but the live page has content). "
                            "Install Yoast SEO or RankMath to enable meta updates."
                        )
        except Exception:
            pass  # fall through to normal handling

    # Pre-flight: nothing can be done — return immediately at zero AI cost
    if not profile["can_improve"]:
        record = PageChange(
            user_id=user_id,
            project_name=project_name,
            cluster_name=cluster_name,
            wp_post_id=post_data["id"],
            wp_post_url=post_data["link"],
            wp_post_type=post_data["type"],
            original_content=post_data["content"],
            new_content=post_data["content"],
            change_summary=profile["blocked_reason"] or "No improvements possible.",
            changes_made=[],
            statistics=None,
            meta_updates=None,
            status="no_action",
        )
        db.add(record)
        db.commit()
        db.refresh(record)
        return record

    knowledge_block = _knowledge_block(db, user_id, project_name) or " | ".join(filter(None, [
        project.business_name,
        project.business_type,
        project.tone_of_voice,
        project.target_audience,
    ])) or "Not specified"

    # Meta-only path: builder/theme pages with a plugin skip analyzer + editor
    if not profile["content_editable"] and profile["meta_editable"]:
        return _run_meta_only(
            keyword, post_data, profile, knowledge_block,
            openai_key, user_id, project_name, cluster_name, project, db,
        )

    # ── Step 1: Analyzer (gpt-4o-mini) ───────────────────────────────────────
    analyzer_msg = f"""## main_keyword
{keyword}

## secondary_keywords
{secondary_keywords}

## hub_url
{pillar_url}

## current_url
{post_data['link']}

## is_homepage
{str(profile['is_homepage']).lower()}

## author
{project.business_name or 'Site Owner'}

## has_yoast
{post_data['has_yoast']}

## has_rankmath
{post_data['has_rankmath']}

## builder
{profile['builder']}

## business_context
{knowledge_block}

## change_history
{_change_history_block(history)}

## html_content (Title: {post_data['title']})
{_strip_html_for_analysis(post_data['content'])}
"""

    raw_analysis = SkillAgent("seo-analyzer", openai_key, model="gpt-4o-mini").run(
        analyzer_msg, timeout=60, json_mode=True
    )
    try:
        analysis = json.loads(raw_analysis)
    except json.JSONDecodeError:
        raise ValueError("Analyzer returned invalid JSON.")

    action_needed = analysis.get("action_needed", False)

    py_stats = {
        "keyword_frequency": _count_keyword_frequency(post_data["content"], keyword),
        "images_missing_alt": _count_images_missing_alt(post_data["content"]),
    }

    changes_made: list[str] = []
    new_content: str = post_data["content"]
    meta_updates: dict | None = None

    # Run editor when content needs improvement OR SEO plugin is present (for meta)
    if action_needed or profile["meta_editable"]:
        # ── Step 2: Editor (gpt-4o) ───────────────────────────────────────────
        editor_msg = f"""## main_keyword
{keyword}

## hub_url
{pillar_url}

## is_homepage
{str(profile['is_homepage']).lower()}

## is_theme_controlled
{str(profile['is_theme_controlled']).lower()}

## author
{project.business_name or 'Site Owner'}

## current_date
{current_date}

## has_yoast
{post_data['has_yoast']}

## has_rankmath
{post_data['has_rankmath']}

## builder
{profile['builder']}

## current_meta_title
{post_data.get('current_meta_title', '')}

## current_meta_description
{post_data.get('current_meta_description', '')}

## business_context
{knowledge_block}

## recommendations
{json.dumps(analysis.get('recommendations', []), indent=2)}

## html_content (Title: {post_data['title']})
{post_data['content']}
"""

        raw_edit = SkillAgent("seo-editor", openai_key, model="gpt-4o").run(
            editor_msg, timeout=120, json_mode=True
        )
        try:
            edit_result = json.loads(raw_edit)
        except json.JSONDecodeError:
            raise ValueError("Editor returned invalid JSON.")

        # Content changes — only apply when content is actually editable
        if profile["content_editable"] and action_needed:
            changes_made = [
                f"{c['type']}: {c['description']}"
                for c in edit_result.get("changes_made", [])
                if isinstance(c, dict) and c.get("status") == "applied"
            ]
            new_content = edit_result.get("new_content") or post_data["content"]

        # Meta changes — only store when plugin is present and values actually changed
        if profile["meta_editable"]:
            meta_title = (edit_result.get("suggested_meta_title") or "").strip()
            meta_description = (edit_result.get("suggested_meta_description") or "").strip()
            current_title = (post_data.get("current_meta_title") or "").strip()
            current_description = (post_data.get("current_meta_description") or "").strip()
            title_changed = meta_title and meta_title != current_title
            desc_changed = meta_description and meta_description != current_description
            if title_changed or desc_changed:
                meta_updates = {
                    "plugin": profile["seo_plugin"],
                    "original_meta_title": current_title or None,
                    "original_meta_description": current_description or None,
                    "suggested_meta_title": meta_title if title_changed else None,
                    "suggested_meta_description": meta_description if desc_changed else None,
                }
                plugin_label = "Yoast" if profile["seo_plugin"] == "yoast" else "RankMath"
                changes_made.append(
                    f"seo_meta: SEO title and description queued for {plugin_label} update."
                )

    # Build the human-readable summary
    has_content_change = new_content != post_data["content"]
    has_meta = bool(meta_updates)

    if has_content_change or has_meta:
        change_summary = analysis.get("summary", "")
    else:
        change_summary = analysis.get("no_action_reason") or "Page is already well-optimized — no changes needed."

    record = PageChange(
        user_id=user_id,
        project_name=project_name,
        cluster_name=cluster_name,
        wp_post_id=post_data["id"],
        wp_post_url=post_data["link"],
        wp_post_type=post_data["type"],
        original_content=post_data["content"],
        new_content=new_content,
        change_summary=change_summary,
        changes_made=changes_made,
        statistics={**(analysis.get("statistics") or {}), **py_stats},
        meta_updates=meta_updates,
        status="pending" if (has_content_change or has_meta) else "no_action",
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    return record


# ── Cron-callable improve helper ──────────────────────────────────────────────

def _run_cron_improve(
    user_id: int,
    project_name: str,
    cluster_name: str,
    cron_job_id: int,
    db: Session,
) -> list[PageChange]:
    """
    Run the improve pipeline for a cluster, invoked by the cron system.
    Returns the list of PageChange records created.
    Does not raise HTTP exceptions — logs errors and skips pages on failure.
    """
    from api.routers.api_keys import get_user_secret
    from core.project import load_project

    try:
        openai_key = get_user_secret("openai", user_id, db)
    except Exception:
        return []

    from core.project import load_project_context
    ctx = load_project_context(user_id, project_name)
    if not ctx:
        return []

    rows = (
        db.query(Keyword)
        .filter(
            Keyword.user_id == user_id,
            Keyword.project_name == project_name,
            Keyword.cluster == cluster_name,
        )
        .all()
    )
    if not rows:
        return []

    hub = next((r for r in rows if r.is_hub), rows[0])
    if not hub.existing_url:
        return []

    try:
        wp = _get_wp_adapter(ctx)
        hub_post_data = wp.find_post_by_url(hub.existing_url)
    except Exception:
        return []

    if not hub_post_data:
        return []

    history = (
        db.query(PageChange)
        .filter(
            PageChange.user_id == user_id,
            PageChange.project_name == project_name,
            PageChange.cluster_name == cluster_name,
        )
        .order_by(PageChange.created_at.desc())
        .limit(10)
        .all()
    )

    seo_plugin = wp.detect_seo_plugin()
    results: list[PageChange] = []
    hub_secondary = ", ".join(r.keyword for r in rows if not r.is_hub) or "None"

    try:
        rec = _run_page_pipeline(
            keyword=hub.keyword,
            secondary_keywords=hub_secondary,
            post_data=hub_post_data,
            pillar_url=hub.suggested_url or hub.existing_url or "",
            history=history,
            project=ctx.config,
            openai_key=openai_key,
            user_id=user_id,
            project_name=project_name,
            cluster_name=cluster_name,
            db=db,
            is_hub=True,
            hub_existing_url=hub.existing_url,
            seo_plugin=seo_plugin,
        )
        rec.cron_job_id = cron_job_id
        rec.source_agent = "cluster_improve"
        db.commit()
        results.append(rec)
    except Exception:
        pass

    return results


# ── Schemas ───────────────────────────────────────────────────────────────────

class AnalyzeRequest(BaseModel):
    cluster_name: str


class ChangeOut(BaseModel):
    id: int
    action_type: str = "page_edit"
    platform: str = "wordpress"
    source_agent: Optional[str] = None
    plan_phase: Optional[str] = None
    cluster_name: str
    wp_post_id: int
    wp_post_url: str
    wp_post_type: str
    change_summary: str
    changes_made: Optional[list[str]] = None
    statistics: Optional[dict] = None
    meta_updates: Optional[dict] = None
    original_content: str
    new_content: str
    draft_title: Optional[str] = None
    draft_slug: Optional[str] = None
    draft_word_count: Optional[int] = None
    plagiarism_flag: bool = False
    plagiarism_score: Optional[float] = None
    plagiarism_status: str = "skipped"
    rejection_reason: Optional[str] = None
    applied_by: Optional[str] = None
    status: str
    created_at: datetime
    approved_at: Optional[datetime] = None
    refresh_status: Optional[dict] = None

    class Config:
        from_attributes = True


def _to_change_out(record: PageChange, history: list[PageChange]) -> ChangeOut:
    """Build ChangeOut with computed refresh_status from pre-analysis history."""
    return ChangeOut(
        id=record.id,
        action_type=record.action_type or "page_edit",
        platform=record.platform or "wordpress",
        source_agent=record.source_agent,
        plan_phase=record.plan_phase,
        cluster_name=record.cluster_name,
        wp_post_id=record.wp_post_id,
        wp_post_url=record.wp_post_url,
        wp_post_type=record.wp_post_type,
        change_summary=record.change_summary,
        changes_made=record.changes_made,
        statistics=record.statistics,
        meta_updates=record.meta_updates,
        original_content=record.original_content,
        new_content=record.new_content,
        draft_title=record.draft_title,
        draft_slug=record.draft_slug,
        draft_word_count=record.draft_word_count,
        plagiarism_flag=record.plagiarism_flag or False,
        plagiarism_score=record.plagiarism_score,
        plagiarism_status=record.plagiarism_status or "skipped",
        rejection_reason=record.rejection_reason,
        applied_by=record.applied_by,
        status=record.status,
        created_at=record.created_at,
        approved_at=record.approved_at,
        refresh_status=_compute_refresh_status(record.wp_post_id, history),
    )


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/analyze", response_model=list[ChangeOut])
def analyze_cluster(
    body: AnalyzeRequest,
    context: ProjectContext = Depends(get_project_context),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    rows = (
        db.query(Keyword)
        .filter(
            Keyword.user_id == current_user.id,
            Keyword.project_name == context.name,
            Keyword.cluster == body.cluster_name,
        )
        .all()
    )
    if not rows:
        raise HTTPException(404, f"Cluster '{body.cluster_name}' not found.")

    hub = next((r for r in rows if r.is_hub), rows[0])
    if not hub.existing_url:
        raise HTTPException(400, "Hub keyword has no existing page URL. Run GSC sync first.")

    wp = _get_wp_adapter(context)

    try:
        hub_post_data = wp.find_post_by_url(hub.existing_url)
    except IntegrationError as e:
        raise HTTPException(502, f"WordPress error: {e}")
    if not hub_post_data:
        raise HTTPException(404, f"Page not found in WordPress for URL: {hub.existing_url}")

    history = (
        db.query(PageChange)
        .filter(
            PageChange.user_id == current_user.id,
            PageChange.project_name == context.name,
            PageChange.cluster_name == body.cluster_name,
        )
        .order_by(PageChange.created_at.desc())
        .limit(10)
        .all()
    )

    project = context.config
    pillar_url = hub.suggested_url or hub.existing_url or ""
    openai_key = get_user_secret("openai", current_user.id, db)

    # Detect SEO plugin once via namespace registry — reliable even when meta values are empty
    seo_plugin = wp.detect_seo_plugin()

    results: list[PageChange] = []

    # ── Hub ───────────────────────────────────────────────────────────────────
    hub_secondary = ", ".join(r.keyword for r in rows if not r.is_hub) or "None"
    try:
        hub_record = _run_page_pipeline(
            keyword=hub.keyword,
            secondary_keywords=hub_secondary,
            post_data=hub_post_data,
            pillar_url=pillar_url,
            history=history,
            project=project,
            openai_key=openai_key,
            user_id=current_user.id,
            project_name=context.name,
            cluster_name=body.cluster_name,
            db=db,
            is_hub=True,
            hub_existing_url=hub.existing_url,
            seo_plugin=seo_plugin,
        )
        results.append(hub_record)
    except (ValueError, Exception) as e:
        raise HTTPException(500, f"Hub analysis failed: {e}")

    # ── Spokes (unique URLs only) ─────────────────────────────────────────────
    seen_urls = {hub.existing_url}
    unique_spokes: list = []
    for r in rows:
        if not r.is_hub and r.existing_url and r.existing_url not in seen_urls:
            seen_urls.add(r.existing_url)
            unique_spokes.append(r)

    for spoke in unique_spokes[:5]:
        try:
            spoke_post_data = wp.find_post_by_url(spoke.existing_url)
            if not spoke_post_data:
                continue
            spoke_secondary = ", ".join(r.keyword for r in rows if r.keyword != spoke.keyword) or "None"
            spoke_record = _run_page_pipeline(
                keyword=spoke.keyword,
                secondary_keywords=spoke_secondary,
                post_data=spoke_post_data,
                pillar_url=pillar_url,
                history=history,
                project=project,
                openai_key=openai_key,
                user_id=current_user.id,
                project_name=context.name,
                cluster_name=body.cluster_name,
                db=db,
                is_hub=False,
                hub_existing_url=hub.existing_url,
                seo_plugin=seo_plugin,
            )
            results.append(spoke_record)
        except Exception:
            continue

    # history was fetched before this run — safe to use for refresh_status without
    # including the records just created above
    return [_to_change_out(r, history) for r in results]


@router.post("/apply/{change_id}", response_model=ChangeOut)
def apply_change(
    change_id: int,
    context: ProjectContext = Depends(get_project_context),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    record = db.query(PageChange).filter(
        PageChange.id == change_id,
        PageChange.user_id == current_user.id,
        PageChange.project_name == context.name,
    ).first()
    if not record:
        raise HTTPException(404, "Change not found.")
    if record.status != "pending":
        raise HTTPException(400, f"Change is already '{record.status}'.")

    action_type = record.action_type or "page_edit"

    # ── new_draft: publish as WP draft post ───────────────────────────────────
    if action_type == "new_draft":
        from integrations.cms.base import PostDraft
        import markdown as md
        wp = _get_wp_adapter(context)
        html = md.markdown(record.new_content, extensions=["tables", "fenced_code"])
        draft = PostDraft(
            title=record.draft_title or "New Article",
            content=html,
            slug=record.draft_slug or "",
            status="draft",
        )
        try:
            created = wp.create_page(draft)
        except IntegrationError as e:
            raise HTTPException(502, f"WordPress draft creation error: {e}")
        # Update record with the real WP post ID and URL
        record.wp_post_id = created.id
        record.wp_post_url = created.url
        record.status = "approved"
        record.approved_at = datetime.utcnow()
        record.applied_by = "subscriber"
        db.commit()
        db.refresh(record)
        history: list = []
        return _to_change_out(record, history)

    wp = _get_wp_adapter(context)
    content_changed = record.original_content != record.new_content

    # Push content only if it actually changed
    if content_changed:
        try:
            _wp_push(wp, record, record.new_content)
        except IntegrationError as e:
            raise HTTPException(502, f"WordPress content update error: {e}")

    # Push SEO meta via Yoast or RankMath if present
    if record.meta_updates:
        mu = record.meta_updates
        raw_title = (mu.get("suggested_meta_title") or "").strip()
        raw_description = (mu.get("suggested_meta_description") or "").strip()
        # Hard-cap title at 60 chars (trim at last word boundary)
        if len(raw_title) > 60:
            raw_title = raw_title[:60].rsplit(" ", 1)[0].rstrip(" |—-")
        try:
            wp.update_seo_meta(
                record.wp_post_id,
                record.wp_post_type,
                mu["plugin"],
                raw_title or None,
                raw_description or None,
            )
        except IntegrationError as e:
            raise HTTPException(502, f"SEO meta update error: {e}")

    record.status = "approved"
    record.approved_at = datetime.utcnow()
    record.applied_by = "subscriber"
    db.commit()
    db.refresh(record)

    # Advance project state to ACTIVE on first approved change
    try:
        from core.state_machine import advance_state
        advance_state(context, "ACTIVE")
    except Exception:
        pass

    history = (
        db.query(PageChange)
        .filter(
            PageChange.user_id == current_user.id,
            PageChange.project_name == context.name,
        )
        .order_by(PageChange.created_at.desc())
        .limit(20)
        .all()
    )
    return _to_change_out(record, history)


@router.post("/rollback/{change_id}", response_model=ChangeOut)
def rollback_change(
    change_id: int,
    context: ProjectContext = Depends(get_project_context),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    record = db.query(PageChange).filter(
        PageChange.id == change_id,
        PageChange.user_id == current_user.id,
        PageChange.project_name == context.name,
    ).first()
    if not record:
        raise HTTPException(404, "Change not found.")
    if record.status != "approved":
        raise HTTPException(400, "Only approved changes can be rolled back.")

    wp = _get_wp_adapter(context)

    # Rollback content if it was changed
    if record.original_content != record.new_content:
        try:
            _wp_push(wp, record, record.original_content)
        except IntegrationError as e:
            raise HTTPException(502, f"WordPress rollback error: {e}")

    # Rollback meta if it was changed
    if record.meta_updates:
        mu = record.meta_updates
        orig_title = mu.get("original_meta_title")
        orig_description = mu.get("original_meta_description")
        try:
            wp.update_seo_meta(
                record.wp_post_id,
                record.wp_post_type,
                mu["plugin"],
                orig_title,
                orig_description,
            )
        except IntegrationError as e:
            raise HTTPException(502, f"SEO meta rollback error: {e}")

    record.status = "rolled_back"
    db.commit()
    db.refresh(record)
    return record


@router.get("/history", response_model=list[ChangeOut])
def get_history(
    context: ProjectContext = Depends(get_project_context),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    records = (
        db.query(PageChange)
        .filter(
            PageChange.user_id == current_user.id,
            PageChange.project_name == context.name,
        )
        .order_by(PageChange.created_at.desc())
        .all()
    )
    return [_to_change_out(r, records) for r in records]


class ClusterStatusOut(BaseModel):
    last_analyzed_at: Optional[datetime]
    days_since_analysis: Optional[int]
    per_page: list[dict]
    aggregate: dict
    message: str


@router.get("/status", response_model=ClusterStatusOut)
def cluster_status(
    cluster_name: str,
    context: ProjectContext = Depends(get_project_context),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Lightweight pre-action check: returns refresh readiness for a cluster without
    running any AI. Frontend shows this before the user clicks Analyze & Suggest.
    """
    history = (
        db.query(PageChange)
        .filter(
            PageChange.user_id == current_user.id,
            PageChange.project_name == context.name,
            PageChange.cluster_name == cluster_name,
            PageChange.status.in_(["pending", "approved", "no_action"]),
        )
        .order_by(PageChange.created_at.desc())
        .limit(20)
        .all()
    )

    if not history:
        return ClusterStatusOut(
            last_analyzed_at=None,
            days_since_analysis=None,
            per_page=[],
            aggregate={"meta_days_remaining": 0, "content_days_remaining": 0},
            message="This cluster has never been analyzed. Run Analyze & Suggest to get started.",
        )

    most_recent = history[0]
    days = max(0, (datetime.utcnow() - most_recent.created_at).days)

    seen: dict[int, PageChange] = {}
    for c in history:
        if c.wp_post_id not in seen:
            seen[c.wp_post_id] = c

    per_page = []
    for wp_post_id, last_change in seen.items():
        rs = _compute_refresh_status(wp_post_id, history)
        per_page.append({
            "wp_post_id": wp_post_id,
            "wp_post_url": last_change.wp_post_url,
            **rs,
        })

    worst_meta = max((p["meta"]["days_remaining"] for p in per_page), default=0)
    worst_content = max((p["content"]["days_remaining"] for p in per_page), default=0)

    if worst_content > 0:
        msg = f"Last analyzed {days} day(s) ago. Meta ready in {worst_meta} day(s). Full content ready in {worst_content} day(s)."
    elif worst_meta > 0:
        msg = f"Last analyzed {days} day(s) ago. Meta refresh ready in {worst_meta} day(s). Content improvement is ready now."
    else:
        msg = f"Last analyzed {days} day(s) ago. All improvements ready to re-run."

    return ClusterStatusOut(
        last_analyzed_at=most_recent.created_at,
        days_since_analysis=days,
        per_page=per_page,
        aggregate={"meta_days_remaining": worst_meta, "content_days_remaining": worst_content},
        message=msg,
    )


class ScanLinksRequest(BaseModel):
    cluster_name: str
    auto_fix: bool = False


class BrokenLinkOut(BaseModel):
    url: str
    type: str
    status_code: int
    suggested_fix: Optional[str] = None


class ScanLinksOut(BaseModel):
    page_url: str
    wp_post_id: int
    total_links: int
    broken_links: list[BrokenLinkOut]
    auto_fixed: list[dict]
    report: str
    fix_change_id: Optional[int] = None


class PatchMetaRequest(BaseModel):
    suggested_meta_title: Optional[str] = None
    suggested_meta_description: Optional[str] = None


@router.post("/scan-links", response_model=ScanLinksOut)
def scan_links(
    body: ScanLinksRequest,
    context: ProjectContext = Depends(get_project_context),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Scan the cluster hub page for broken links.
    Checks up to 30 internal + 10 external links.
    With auto_fix=true, internal 404s with a found replacement are queued as a
    pending PageChange (same approval flow as content improvements).
    """
    last_change = (
        db.query(PageChange)
        .filter(
            PageChange.user_id == current_user.id,
            PageChange.project_name == context.name,
            PageChange.cluster_name == body.cluster_name,
            PageChange.status.in_(["pending", "approved"]),
        )
        .order_by(PageChange.created_at.desc())
        .first()
    )
    if not last_change:
        raise HTTPException(
            400,
            "No analysis found for this cluster. Run Analyze & Suggest first.",
        )

    wp = _get_wp_adapter(context)
    try:
        if last_change.wp_post_type == "page":
            post_data = wp.get_page(last_change.wp_post_id)
        else:
            post_data = wp.get_post(last_change.wp_post_id)
    except IntegrationError as e:
        raise HTTPException(502, f"WordPress error fetching page: {e}")

    content  = post_data["content"]
    page_url = post_data["link"]
    all_links = _extract_links(content, page_url)

    internal_links = [l for l in all_links if l["type"] == "internal"][:30]
    external_links = [l for l in all_links if l["type"] == "external"][:10]
    links_to_check = internal_links + external_links

    broken: list[BrokenLinkOut] = []
    for link in links_to_check:
        status = _check_link_status(link["url"])
        if status in (404, 410):
            fix = None
            if link["type"] == "internal":
                slug = urlparse(link["url"]).path.rstrip("/").split("/")[-1]
                try:
                    fix = wp.find_url_by_slug(slug)
                except IntegrationError:
                    pass
            broken.append(BrokenLinkOut(
                url=link["url"],
                type=link["type"],
                status_code=status,
                suggested_fix=fix,
            ))

    # Auto-fix: replace broken internal hrefs that have a known replacement.
    # Creates a pending PageChange rather than pushing immediately.
    auto_fixed: list[dict] = []
    fix_change_id: int | None = None
    if body.auto_fix and broken:
        new_content = content
        for b in broken:
            if b.type == "internal" and b.suggested_fix:
                for q in ('"', "'"):
                    old_token = f'href={q}{b.url}{q}'
                    new_token = f'href={q}{b.suggested_fix}{q}'
                    if old_token in new_content:
                        new_content = new_content.replace(old_token, new_token)
                        auto_fixed.append({"old_url": b.url, "new_url": b.suggested_fix})
                        break

        if new_content != content:
            fix_record = PageChange(
                user_id=current_user.id,
                project_name=context.name,
                cluster_name=body.cluster_name,
                wp_post_id=post_data["id"],
                wp_post_url=page_url,
                wp_post_type=post_data["type"],
                original_content=content,
                new_content=new_content,
                change_summary=f"Broken link fix: {len(auto_fixed)} internal link(s) updated.",
                changes_made=[f"link_fix: {f['old_url']} → {f['new_url']}" for f in auto_fixed],
                statistics=None,
                meta_updates=None,
                status="pending",
            )
            db.add(fix_record)
            db.commit()
            db.refresh(fix_record)
            fix_change_id = fix_record.id

    # seo-technical agent produces the impact report
    openai_key = get_user_secret("openai", current_user.id, db)
    if broken:
        report_msg = f"""## Broken Links Scan

Page: {page_url}
Links checked: {len(links_to_check)} ({len(internal_links)} internal, {len(external_links)} external)
Broken: {len(broken)}
Auto-fixed in this run: {len(auto_fixed)}

## Broken link details
{json.dumps(
    [{"url": b.url, "type": b.type, "status_code": b.status_code, "suggested_fix": b.suggested_fix}
     for b in broken],
    indent=2
)}

Provide:
1. SEO impact — which broken links hurt rankings most (internal hub/pillar links are highest priority)
2. Fix priority (high / medium / low) for each broken link
3. Overall link health summary in 2-3 sentences
"""
        report = SkillAgent("seo-technical", openai_key, model="gpt-4o").run(
            report_msg, timeout=60
        )
    else:
        report = (
            f"No broken links found. "
            f"{len(links_to_check)} link(s) checked "
            f"({len(internal_links)} internal, {len(external_links)} external) — all returned valid responses."
        )

    return ScanLinksOut(
        page_url=page_url,
        wp_post_id=post_data["id"],
        total_links=len(all_links),
        broken_links=broken,
        auto_fixed=auto_fixed,
        report=report,
        fix_change_id=fix_change_id,
    )


@router.patch("/patch/{change_id}", response_model=ChangeOut)
def patch_meta(
    change_id: int,
    body: PatchMetaRequest,
    context: ProjectContext = Depends(get_project_context),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Edit suggested meta title/description before pushing to WordPress.
    Only allowed on pending changes that have meta_updates.
    Title is hard-capped at 60 chars; description at 160.
    """
    record = db.query(PageChange).filter(
        PageChange.id == change_id,
        PageChange.user_id == current_user.id,
        PageChange.project_name == context.name,
    ).first()
    if not record:
        raise HTTPException(404, "Change not found.")
    if record.status != "pending":
        raise HTTPException(400, f"Only pending changes can be edited (current status: '{record.status}').")
    if not record.meta_updates:
        raise HTTPException(400, "This change has no meta updates to edit.")

    mu = dict(record.meta_updates)

    if body.suggested_meta_title is not None:
        title = body.suggested_meta_title.strip()
        if len(title) > 60:
            title = title[:60].rsplit(" ", 1)[0].rstrip(" |—-")
        mu["suggested_meta_title"] = title or None

    if body.suggested_meta_description is not None:
        desc = body.suggested_meta_description.strip()
        if len(desc) > 160:
            desc = desc[:160].rsplit(" ", 1)[0].rstrip()
        mu["suggested_meta_description"] = desc or None

    record.meta_updates = mu
    db.commit()
    db.refresh(record)
    return record
